# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495fd43f95597017fe487a3a9e8f8029ed94ad1e099038aed24dde0798765467d2d737bd2b3a5b842e4dc345365d94a4d8df11f49d2eba5f47970f13b6c20d48

test:
  secret_key_base: a33f0ed6794b560cf6497bd3e7d41aeeed88c4982fc3198cd87e526b794dbec191f2bc6722467a1d292a99ff7e38d17fc6f23497c80f7846a2b240ed3e65edf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
